// AUTO-GENERATED by fetch_portfolio_westock.py — 勿手动编辑
window.PORTFOLIO_DATA = {
  "updated_at": "2026-09-13 15:19",
  "source": "westock-mcp",
  "account": {
    "name": "练习赛组合",
    "total_assets": 985163.39,
    "market_value": 38833.0,
    "available_cash": 946330.39,
    "total_profit": -14836.6,
    "total_profit_rate": -1.48
  },
  "positions": [
    {
      "code": "sz301583",
      "name": "托伦斯",
      "market": "sz",
      "qty": 100,
      "cost_price": 167.3,
      "live_price": 110.33,
      "buy_date": "",
      "note": ""
    },
    {
      "code": "sh688548",
      "name": "广钢气体",
      "market": "sh",
      "qty": 1000,
      "cost_price": 36.939,
      "live_price": 27.8,
      "buy_date": "",
      "note": ""
    }
  ],
  "update_time": "2026-09-13 15:19:00"
};
