#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
sync_westock_portfolio.py — westock 持仓云端同步守护脚本

数据流：
  westock MCP (portfolio_paper_positions + portfolio_paper_portfolio + data_quote)
      → 本脚本（合并 PORTFOLIO_COST.js 真实成本基准）
      → data/PORTFOLIO.js
      → git commit + push origin main（仅当数据实质变化或需心跳时）

用法（由 agent/自动化调用）：
  python sync_westock_portfolio.py --positions '@file' --quotes '@file' --account '@file' [--push]

--push 存在时才执行 git add/commit/push；否则仅生成文件并打印 diff 简报。
"""
import json
import os
import re
import subprocess
import sys
from datetime import datetime

# 把仓库根目录加入路径，以便导入 fetch_portfolio_westock
HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from fetch_portfolio_westock import (
    _load_arg,
    build_portfolio_data,
    portfolio_data_signature,
    OUT_FILE,
)


def load_existing_portfolio():
    """解析当前 data/PORTFOLIO.js 中的 window.PORTFOLIO_DATA。"""
    try:
        with open(OUT_FILE, "r", encoding="utf-8") as f:
            txt = f.read()
        m = re.search(r"window\.PORTFOLIO_DATA\s*=\s*", txt)
        if not m:
            return None
        start = txt.index("{", m.end())
        depth = 0
        end = start
        for i in range(start, len(txt)):
            if txt[i] == "{":
                depth += 1
            elif txt[i] == "}":
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break
        return json.loads(txt[start:end])
    except Exception as e:
        print("WARN load_existing_portfolio:", e, file=sys.stderr)
    return None


def write_portfolio_js(data):
    js = "// AUTO-GENERATED by fetch_portfolio_westock.py — 勿手动编辑\n"
    js += "window.PORTFOLIO_DATA = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(js)


def git_push_portfolio(commit_msg):
    """单文件隔离推送，避免与工作树其它并发改动冲突。"""
    repo = HERE
    tmp_index = os.path.join(repo, ".git", "tmp_westock_idx")
    env = os.environ.copy()
    env["GIT_INDEX_FILE"] = tmp_index

    def run(cmd, **kw):
        return subprocess.run(cmd, cwd=repo, env=env, text=True, capture_output=True, **kw)

    # 清理旧 index
    try:
        os.remove(tmp_index)
    except FileNotFoundError:
        pass

    # 基于 origin/main 构建隔离 index
    r = run(["git", "fetch", "origin", "main"])
    if r.returncode != 0:
        print("ERROR git fetch:", r.stderr, file=sys.stderr)
        return False

    r = run(["git", "read-tree", "origin/main"])
    if r.returncode != 0:
        print("ERROR git read-tree:", r.stderr, file=sys.stderr)
        return False

    # 计算 PORTFOLIO.js blob 并写入 index
    r = run(["git", "hash-object", "-w", "data/PORTFOLIO.js"])
    if r.returncode != 0 or not r.stdout.strip():
        print("ERROR git hash-object:", r.stderr, file=sys.stderr)
        return False
    blob = r.stdout.strip()

    r = run(["git", "update-index", "--add", "--cacheinfo", "100644", blob, "data/PORTFOLIO.js"])
    if r.returncode != 0:
        print("ERROR git update-index:", r.stderr, file=sys.stderr)
        return False

    r = run(["git", "write-tree"])
    if r.returncode != 0 or not r.stdout.strip():
        print("ERROR git write-tree:", r.stderr, file=sys.stderr)
        return False
    tree = r.stdout.strip()

    r = run(["git", "commit-tree", tree, "-p", "origin/main", "-m", commit_msg])
    if r.returncode != 0 or not r.stdout.strip():
        print("ERROR git commit-tree:", r.stderr, file=sys.stderr)
        return False
    commit = r.stdout.strip()

    # 推送（带简单重试）
    for attempt in range(1, 4):
        r = run(["git", "push", "origin", f"{commit}:main"])
        if r.returncode == 0:
            print("OK pushed", commit[:12], "to origin/main")
            # 收尾：只删除临时 index，**不再移动本地 HEAD**。
            # 【2026-08-24 修复·数据回滚地雷】原实现为 git reset --soft origin/main：
            #   ① --soft 只移动 HEAD、不重排主 index（且此处 env 带 GIT_INDEX_FILE，
            #      即便改 --mixed 也只会写临时 index，主 index 依旧停留在旧树）；
            #   ② HEAD 被推到最新 origin/main 后，主 index 仍是旧树 →
            #      git status 出现 100+ 个「已暂存」的**旧版本**文件（含 index.html 与
            #      raw_data 删除项）；
            #   ③ 任何脚本执行不带 pathspec 的 git commit -m 都会把这批旧版本一并提交，
            #      造成整站数据回滚 + 文件被删。
            # 现改为不动 HEAD：主 index 与 HEAD 始终一致，暂存区恒为空，地雷不再生成。
            # 本地 HEAD 落后 origin/main 属预期（各管线自身会 fetch + rebase 对齐）。
            try:
                os.remove(tmp_index)
            except FileNotFoundError:
                pass
            return True
        print(f"WARN push attempt {attempt} failed:", r.stderr, file=sys.stderr)
    print("ERROR push failed after 3 attempts", file=sys.stderr)
    return False


def is_trading_time(dt=None):
    """判断是否为 A股 工作日交易时段（粗略：周一到周五 09:00-16:00）。"""
    if dt is None:
        dt = datetime.now()
    if dt.weekday() >= 5:
        return False
    hm = dt.hour * 100 + dt.minute
    return 900 <= hm <= 1600


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--positions", default="{}")
    ap.add_argument("--quotes", default="{}")
    ap.add_argument("--account", default="")
    ap.add_argument("--push", action="store_true", help="执行 git push（自动化使用）")
    ap.add_argument("--heartbeat-min", type=int, default=30, help="无数据变化时，最长多少分钟强制提交一次（默认30）")
    args = ap.parse_args()

    new_data = build_portfolio_data(args.positions, args.quotes, args.account)
    if not new_data.get("positions") and not args.positions.strip("{} "):
        print("ERROR no positions data", file=sys.stderr)
        sys.exit(1)

    old_data = load_existing_portfolio()

    changed = False
    if old_data is None:
        changed = True
        reason = "首次生成"
    else:
        old_sig = portfolio_data_signature(old_data)
        new_sig = portfolio_data_signature(new_data)
        if old_sig != new_sig:
            changed = True
            reason = "持仓/账户数据变化"
        else:
            reason = "数据无变化"

    # 心跳：即使数据无变化，超过 heartbeat-min 也强制更新 updated_at 并提交
    heartbeat = False
    if not changed and old_data and args.push:
        last_ts = old_data.get("updated_at", "")
        try:
            last_dt = datetime.strptime(last_ts, "%Y-%m-%d %H:%M")
            elapsed_min = (datetime.now() - last_dt).total_seconds() / 60
            if elapsed_min >= args.heartbeat_min:
                heartbeat = True
                reason = f"心跳（{int(elapsed_min)}分钟未更新）"
        except Exception:
            heartbeat = True
            reason = "心跳（时间戳异常）"

    need_write = changed or heartbeat or old_data is None
    if not need_write:
        print("SKIP no change, last:", old_data.get("updated_at"), "reason:", reason)
        sys.exit(0)

    write_portfolio_js(new_data)
    print("OK wrote", OUT_FILE, "positions:", len(new_data["positions"]), "updated_at:", new_data["updated_at"], "reason:", reason)

    if not args.push:
        print("INFO --push not set, skip git push")
        sys.exit(0)

    # 非交易时间不 push（避免无意义夜间提交）
    if not is_trading_time():
        print("INFO not trading time, skip push; file updated locally")
        sys.exit(0)

    msg = f"data: westock 持仓同步 ({new_data['updated_at']})"
    if changed:
        msg += " [变化]"
    elif heartbeat:
        msg += " [心跳]"

    ok = git_push_portfolio(msg)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
