name: Test With Permissions

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
